Initial edits for CLI section
wpengine/headless-docs pull request #43
Opened 2021-02-26 16:08 UTC by DonNateR

2021-02-26 16:21 UTC, matt-landers commented on guides/getting-started/deploy-app/README.md
> +Now that we have created a [simple app](/guides/getting-started/create-app) up and running, let's deploy it to the Headless Platform.
created a simple app _that is_ up and running

2021-02-26 16:24 UTC, matt-landers requested changes
See comments

2021-02-26 16:32 UTC, DonNateR commented
@matt-landers: Should be good to go now.

2021-03-22 16:45 UTC, matt-landers approved these changes

2021-03-24 14:44 UTC, merged